Show scrollbar from the side on wide screens
yako-dev/flutter-settings-ui pull request #125
Opened 2022-06-01 12:14 UTC by M-ixai-L

https://github.com/yako-dev/flutter-settings-ui/issues/121

![image](https://user-images.githubusercontent.com/92673427/171401915-f4b506f6-151a-42c3-b16b-ae90cf05765b.png)

2022-06-02 11:23 UTC, yadaniyil requested changes

2022-06-02 11:23 UTC, yadaniyil commented on example/android/app/src/debug/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.INTERNET"/>
why does the lib need internet permission?

2022-06-02 11:23 UTC, yadaniyil commented on example/android/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip
not sure it's good to downgrade gradle verison, but it's ok I guess

2022-06-02 11:23 UTC, yadaniyil commented on example/lib/screens/gallery_screen.dart
> +                title: Text(
why?

2022-06-02 11:25 UTC, yadaniyil commented
conflicts @M-ixai-L

2022-06-05 06:45 UTC, thomas725 approved these changes
I'd love to see this bugfix released :)

Not that I understand what this code does, I just want to see the result shown in the screenshot in the pull request @ https://github.com/yako-dev/flutter-settings-ui/pull/125 in my project's usage of your library too ;)

2022-06-12 21:41 UTC, merged